#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# vi: set expandtab shiftwidth=4 :

#まだ途中

# ldapdeletemiyabi.py

from libldap import LDAP

URI = 'ldap://ldap.example.jp'
BIND_DN = 'cn=master,dc=example,dc=jp'
BASE_DN = 'dc=example,dc=jp'
BIND_PASS = 'secret123'

def main():
    print("call main")
    result = delmiyabi2()
    print("result")

def delmiyabi2():
    print("call dlmiyabi2")
    ld = LDAP(URI)
    ld.bind(BIND_DN,BIND_PASS)
    result = ld.delete('uid=miyabi2,ou=Users,dc=example,dc=jp')
    ld.unbind()
    return result

print("global")
main()
